### PR TITLE
changing load model

### LINKED ISSUE #121: Change load default library to use cpp one

### PR DESCRIPTION
**Pull request by marcochiaramello**
Closes #121

### CODE REVIEW

**Review by cossartque — APPROVED** [review]
Thanks for the update of the model.
Regarding the outputIIDM.xml of the test cases, we see no change at all ?

**Comment by marcochiaramello** [comment]
the differences in value are extremely small, of order 10^-8, those do not break tests

**Review by rosiereflo — APPROVED** [review]

**Comment by rosiereflo** [comment]
can we merge this one?

**Comment by cossartque** [comment]
> can we merge this one?

Yes we can

**Pull request merged**
